server:
  port: 8888
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  datasource:
    url: jdbc:sqlserver://10.202.161.12:1433;databaseName=db_datasync
framework: 
  longTermMaxSize: 100
  mediumTermMaxSize: 500
  shortTermMaxSize: 2
  